### PR TITLE
New layout 

### PR DESCRIPTION
**Pull request by fashaikh**
Addresses  #36 #37 #45 #46 #47 

@sdras @jefking  @ColbyTresness  This is deployed at https://serverlesslibrarytest.azurewebsites.net .

### CODE REVIEW

**Comment by fashaikh** [comment]
tagging @msnehagup @pravagar

**Comment by sdras** [comment]
I like where this is going! Much better.

Please use an SVG rather than a lossy jpg for "Deploy to Azure" and make sure the contrast is suitable (almost 10% of men are colorblind) This contrast is a hard fail: http://jxnblk.com/colorable/demos/text/?background=%235bc0de&foreground=%23fff

That favicon is 🔥

**Comment by sdras** [comment]
Ah, the modal should also freeze the window content and fade the background out while it's active. Plus clicking outside should close it, or you should move focus so that the screenreader users aren't trapped.

**Comment by fashaikh** [comment]
Thanks Sarah! Will address them soon.
Here is my list of nits I'm planning to work on 
c-search padding left 15px; -> Match left padding in search bar
javascript capital J in cards
right align dropdowns and spacing between them
Function App
Spacing above and below command bar 
Sync box shadow with card shadow

**Comment by ColbyTresness** [comment]
A few other nits:

1. Can we add some more space between the cards/shrink them very slightly? It feels a bit busy.
2. javascript should be JavaScript
3. CSharp should be C#
4. Function app should be Function App

**Comment by ColbyTresness** [comment]
Also: there's a small bit of white space around the deploy to azure button, and the user account pictures should be masked to a circle (with a border, to distinguish between MS and non MS users).

Also, we should make the color contrast greater between the top bar of the card and the background.

**Comment by ColbyTresness** [comment]
Also, the text inside the card should be left aligned with the logos.

Sorry for the spam just taking notes in a meeting with the designers. Let's chat about this in person tomorrow!

**Comment by joescars** [comment]
Can you change the cursor when you hover over 'deploy to azure' to a pointer? ```cursor:pointer``` . Right now when you hover on the button it's not obvious that its clickable.

**Comment by pravagar** [comment]
>           Also the pop up button really needs work - we can chat more about this later as well. Also it doesn't have a hover over on the button, and it should to indicate that we're about to click on something.
> Also we tried to deploy something, and it deployed the wrong thing... can you check the logic there?
I am working on the deployment issue.

**Comment by fashaikh** [comment]
A lot of the changes are updated and deployed to
https://serverlesslibrarytest.azurewebsites.net/

**Pull request merged**
